### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by kaishijeng** [vikrant7/mobile-vod-bottleneck-lstm#11]
I use the following script to do training:

python3 train_mvod_basenet.py --datasets /home/sma/2TB/VID2015/ILSVRC/Data/VID  --batch_size 60 --num_epochs 30 --width_mult 1

But got errors below:

2019-12-07 00:37:48,954 - root - INFO - Namespace(base_net_lr=None, batch_size=60, cache_path=None, checkpoint_folder='models/', datasets='/home/sma/2TB/VID2015/ILSVRC/Data/VID', debug_steps=100, gamma=0.1, lr=0.003, milestones='80,100', momentum=0.9, num_epochs=30, num_workers=4, pretrained=None, resume=None, scheduler='multi-step', ssd_lr=None, t_max=120, use_cuda=True, validation_epochs=5, weight_decay=0.0005, width_mult=1.0)
2019-12-07 00:37:48,954 - root - INFO - Prepare training datasets.
Traceback (most recent call last):
  File "train_mvod_basenet.py", line 206, in <module>
    target_transform=target_transform)
  File "/home/sma/2TB/RCN/mobile-vod-bottleneck-lstm/datasets/vid_dataset_new.py", line 190, in __init__
    self.root = pathlib.Path(root)
  File "/home/sma/anaconda3/envs/directron2/lib/python3.6/pathlib.py", line 1001, in __new__
    self = cls._from_parts(args, init=False)
  File "/home/sma/anaconda3/envs/directron2/lib/python3.6/pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/sma/anaconda3/envs/directron2/lib/python3.6/pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Any idea why this happens?
Thanks,

**Comment by AmitYadu** [comment]
i got the same error ?

**Comment by stvogel** [comment]
Just have a look at train_mvod_basenet.py. You also need to provide the path to a cache-directory when you run train_mvod_basenet.py with `--cache_path /tmp`
