### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by tuyaxin** [vikrant7/mobile-vod-bottleneck-lstm#12]
python train_mvod_basenet.py --datasets /home/feimiao/Documents/tuyaxin/mobile-vod-bottleneck-lstm-master/ILSVRC/ --batch_size 60 --num_epochs 30 --width_mult 1
2019-12-10 16:59:33,761 - root - INFO - Namespace(base_net_lr=None, batch_size=60, cache_path=None, checkpoint_folder='models/', datasets='/home/feimiao/Documents/tuyaxin/mobile-vod-bottleneck-lstm-master/ILSVRC/', debug_steps=100, gamma=0.1, lr=0.003, milestones='80,100', momentum=0.9, num_epochs=30, num_workers=4, pretrained=None, resume=None, scheduler='multi-step', ssd_lr=None, t_max=120, use_cuda=True, validation_epochs=5, weight_decay=0.0005, width_mult=1.0)
2019-12-10 16:59:33,763 - root - INFO - Prepare training datasets.
Traceback (most recent call last):
  File "train_mvod_basenet.py", line 207, in <module>
    target_transform=target_transform)
  File "/home/feimiao/Documents/tuyaxin/mobile-vod-bottleneck-lstm-master/datasets/vid_dataset_new.py", line 190, in __init__
    self.root = pathlib.Path(root)
  File "/home/feimiao/anaconda3/envs/MVOD/lib/python3.7/pathlib.py", line 1003, in __new__
    self = cls._from_parts(args, init=False)
  File "/home/feimiao/anaconda3/envs/MVOD/lib/python3.7/pathlib.py", line 658, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/feimiao/anaconda3/envs/MVOD/lib/python3.7/pathlib.py", line 642, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

NoneType error occurred when I trained．In my opinion, ｔhe problem lies in the 'train_VID_gt_db.pkl' file. How can I get the 'train_VID_gt_db.pkl' file?
Thank ａｎｄ hope for your reply.

**Comment by devarajnadiger** [comment]
Replace root in line 190 with root dataset folder path i.e. 'data'

**Comment by alejodosr** [comment]
You can provide a cache path with argument `--cache_path`
