### ISSUE TITLE
error in training

### ISSUE THREAD

**Issue by AmitYadu** [vikrant7/mobile-vod-bottleneck-lstm#14]
python train_mvod_basenet.py --datasets /home/amit/ILSVRC2015_VID_initial/ILSVRC201  --batch_size 60 --num_epochs 30 --width_mult 1
2020-01-03 10:40:12,053 - root - INFO - Namespace(base_net_lr=None, batch_size=60, cache_path=None, checkpoint_folder='models/', datasets='/home/amit/ILSVRC2015_VID_initial/ILSVRC201', debug_steps=100, gamma=0.1, lr=0.003, milestones='80,100', momentum=0.9, num_epochs=30, num_workers=4, pretrained=None, resume=None, scheduler='multi-step', ssd_lr=None, t_max=120, use_cuda=True, validation_epochs=5, weight_decay=0.0005, width_mult=1.0)
2020-01-03 10:40:12,204 - root - INFO - Prepare training datasets.
Traceback (most recent call last):
  File "train_mvod_basenet.py", line 207, in <module>
    target_transform=target_transform)
  File "/home/amit/Downloads/mobile-vod-bottleneck-lstm-master/datasets/vid_dataset_new.py", line 190, in __init__
    self.root = pathlib.Path(root)
  File "/home/amit/anaconda3/lib/python3.7/pathlib.py", line 1010, in __new__
    self = cls._from_parts(args, init=False)
  File "/home/amit/anaconda3/lib/python3.7/pathlib.py", line 665, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/amit/anaconda3/lib/python3.7/pathlib.py", line 649, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

please help

**Comment by deepsamal** [comment]
@AmitYadu I am facing the same issue. How did you solve it?
