### ISSUE TITLE
train failed

### ISSUE THREAD

**Issue by bryanlinnan** [vikrant7/mobile-vod-bottleneck-lstm#3]
i tried to use your code to train, failed like below:
-------------------------------------------------------------------------------
python train_mvod_basenet.py --datasets E:\ImageNetVID\ILSVRC2015 --batch_size 30 --num_epochs 10 --width_mult 1
2019-10-15 07:37:33,897 - root - INFO - Use Cuda.
2019-10-15 07:37:33,897 - root - INFO - Namespace(base_net_lr=None, batch_size=30, checkpoint_folder='models/', datasets='E:\\ImageNetVID\\ILSVRC2015', debug_steps=100, gamma=0.1, lr=0.003, milestones='80,100', momentum=0.9, num_epochs=10, num_workers=4, pretrained=None, resume=None, scheduler='multi-step', ssd_lr=None, t_max=120, use_cuda=True, validation_epochs=5, weight_decay=0.0005, width_mult=1.0)
2019-10-15 07:37:34,100 - root - INFO - Prepare training datasets.
2019-10-15 07:37:34,507 - root - INFO - using default Imagenet VID classes.
2019-10-15 07:37:34,507 - root - INFO - Stored labels into file models/vid-model-labels.txt.
2019-10-15 07:37:34,507 - root - INFO - Train dataset size: 76859
2019-10-15 07:37:34,507 - root - INFO - Prepare Validation datasets.
2019-10-15 07:37:34,569 - root - INFO - using default Imagenet VID classes.
2019-10-15 07:37:34,569 - root - INFO - <datasets.vid_dataset.ImagenetDataset object at 0x0000021307FEEE80>
2019-10-15 07:37:34,569 - root - INFO - validation dataset size: 11080
2019-10-15 07:37:34,569 - root - INFO - Build network.
2019-10-15 07:37:34,678 - root - INFO - Initializing weights of base net
2019-10-15 07:37:34,694 - root - INFO - Initializing weights of SSD
2019-10-15 07:37:39,750 - root - INFO - Learning rate: 0.003, Base net learning rate: 0.003, Extra Layers learning rate: 0.003.
2019-10-15 07:37:39,766 - root - INFO - Uses MultiStepLR scheduler.
2019-10-15 07:37:39,766 - root - INFO - Start training from epoch 0.
Traceback (most recent call last):
  File "train_mvod_basenet.py", line 282, in <module>
    device=DEVICE, debug_steps=args.debug_steps, epoch=epoch)
  File "train_mvod_basenet.py", line 115, in train
    for i, data in enumerate(loader):
  File "D:\Tool\Anaconda\Anaconda3-5.2.0\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "D:\Tool\Anaconda\Anaconda3-5.2.0\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "D:\Tool\Anaconda\Anaconda3-5.2.0\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Tool\Anaconda\Anaconda3-5.2.0\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Tool\Anaconda\Anaconda3-5.2.0\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Tool\Anaconda\Anaconda3-5.2.0\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Tool\Anaconda\Anaconda3-5.2.0\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'TrainAugmentation.__init__.<locals>.<lambda>'

D:\Work\Mobile Video Object Detection with Temporally-Aware Feature Maps\mobile-vod-bottleneck-lstm-master>2019-10-15 07:37:40,671 - root - INFO - Use Cuda.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Tool\Anaconda\Anaconda3-5.2.0\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Tool\Anaconda\Anaconda3-5.2.0\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
-------------------------------------------------------------------------------------

all dependency prepared
Opencv
Python3.6
Pytorch1.0

by the way, i work under windows

could you help tell what is the problem?

**Comment by vikrant7** [comment]
Hi @bryanlinnan 
Since you were successful in training the model, I am closing this issue now.
